// Generated by CoffeeScript 1.9.3
(function() {
  var Gallery;

  Gallery = function() {
    this.Init = function(base) {
      return this.readDirectory(base);
    };
    this.readDirectory = function(base) {
      return $.get("/php/request_gal.php?dir=" + (base != null ? base : ""), function(data) {
        return $("#gal_output").html(data + '<script src="js/slimbox2.js" type="text/javascript"></script><script>InitGallery();</script>');
      }).fail(function() {
        return $("#gal_output").html("<h1>Uuups Something went wrong!</h1>");
      });
    };
    return this;
  };

  (function($, Gallery) {
    var get_page, get_url, init, init_banner, init_border, init_buttons, put_page, redirect;
    get_url = function() {
      var query;
      if (document.location.search.substr(1)) {
        query = {};
        $.each(document.location.search.substr(1).split('&'), function(c, q) {
          var i;
          i = q.split('=');
          return query[i[0].toString()] = i[1].toString();
        });
        return query;
      }
    };
    get_page = function(page) {
      return $.get("content/" + page, function(data) {
        return put_page(data);
      }).fail(function() {
        return get_page("404.html");
      });
    };
    put_page = function(data) {
      $("#container").fadeOut(0).html(data).fadeIn(500);
      return init();
    };
    $(document).ready(function() {
      return (function(url) {
        var ref;
        get_page((ref = url['page']) != null ? ref : "index.html");
        if (url['page'] === "galeria.html") {
          return (new Gallery).Init(url['gal_dir']);
        }
      })(get_url());
    });
    $(window).resize(function() {
      return init_border();
    });
    init = function() {
      init_buttons();
      init_banner();
      return init_border();
    };
    init_border = function() {
      return $("#border").width(function() {
        return ($(window).width() - 25) + "px";
      }).height(function() {
        return ($(window).height() - 25) + "px";
      });
    };
    init_buttons = function() {
      return $(".icon").mouseenter(function(event) {
        return $(this).addClass(function() {
          return "hovered";
        });
      }).mouseleave(function(event) {
        return $(this).removeClass(function() {
          return "hovered";
        });
      }).click(function(event) {
        redirect($(this).parent().attr("href"));
        return false;
      });
    };
    init_banner = function() {
      return $("#banner").click(function(event) {
        return redirect('?page=index.html');
      });
    };
    return redirect = function(target) {
      return $("#container").fadeOut(500, function() {
        return $(location).attr('href', target);
      });
    };
  })(jQuery, Gallery);

}).call(this);
