// Generated by CoffeeScript 1.9.3
(function() {
  (function($) {
    var get_page, get_url, init, init_buttons, put_page;
    get_url = function() {
      var query;
      if (document.location.search.substr(1)) {
        query = {};
        $.each(document.location.search.substr(1).split('&'), function(c, q) {
          var i;
          i = q.split('=');
          return query[i[0].toString()] = i[1].toString();
        });
        return query['page'];
      }
    };
    get_page = function(page) {
      return $.get("content/" + page, function(data) {
        return put_page(data);
      }).fail(function() {
        alert("Požadovaná stránka sa nenašla!");
        return get_page("index.html");
      });
    };
    put_page = function(data) {
      $("#container").fadeOut(0).html(data).fadeIn(500);
      return init();
    };
    $(document).ready(function() {
      return (function(url) {
        if (url != null) {
          return get_page(url);
        } else {
          return get_page("index.html");
        }
      })(get_url());
    });
    init = function() {
      return init_buttons();
    };
    return init_buttons = function() {
      return $(".icon").mouseenter(function(event) {
        return $(this).addClass(function() {
          return "hovered";
        });
      }).mouseleave(function(event) {
        return $(this).removeClass(function() {
          return "hovered";
        });
      }).click(function(event) {
        var target;
        target = $(this).parent().attr("href");
        $("#container").fadeOut(500, function() {
          return $(location).attr('href', target);
        });
        return false;
      });
    };
  })(jQuery);

}).call(this);
